# Generated by Django 5.0.9 on 2024-09-29 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_materials', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Material',
        ),
    ]
