# Generated by Django 5.0.9 on 2024-09-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='code',
            field=models.CharField(default=0.0005263157894736842, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('assignments', 'Assignments'), ('labs', 'Labs'), ('lectures', 'Lectures'), ('references', 'References')], max_length=20),
        ),
    ]
